Layout and views/Controllers/FeverCheckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Layout_and_views.Models;

namespace Layout_and_views.Controllers
{
    public class FeverCheckController : Controller
    {
        // GET: FewerCheck
        public ActionResult FeverCheck()
        {
            return View(new FeverCheckController());
        }
    }
}

Layout and views/Controllers/GuessingController.cs
using Layout_and_views.Helpers;
using Layout_and_views.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Layout_and_views.Controllers
{
    public class GuessingController : Controller
    {
        private static Random rng = new Random();

        [HttpGet]
        public ActionResult Index()
        {
            this.Session["Answer"] = rng.Next(1, 101);
            this.Session["GuessList"] = new List<int>();
            Guess guess = new Guess
            {
                Answer = (int)this.Session["Answer"],
            };
            HighScore highScore;
            
            var requestCookie = Request.Cookies["GuessingGame"];
            if (!CookieHelper.CookieExists(requestCookie))
            {
                highScore = new HighScore();
                var responseCookie = Response.Cookies["GuessingGame"];
                CookieHelper.WriteCookie(responseCookie,"HighScore", highScore, DateTime.Now.AddYears(1));
            }
            else
            {
                try
                {
                    highScore = CookieHelper.ReadCookie<HighScore>(requestCookie, "HighScore");
                    if(highScore == null)
                    {
                        throw (new Exception("Trash data in cookie"));
                    }
                }
                catch
                {
                    highScore = new HighScore();
                    var responseCookie = Response.Cookies["GuessingGame"];
                    CookieHelper.WriteCookie(responseCookie, "HighScore", highScore, DateTime.Now.AddYears(1));
                }
            }
            return View(new GuessAndHighScore(highScore,guess));
        }
        [HttpPost]
        public ActionResult Index(GuessAndHighScore model)
        {
            if (ModelState.IsValid && !this.Session.IsNewSession)
            {
                model.Guess.Result = Guess.HighOrLow((int)this.Session["Answer"], model.Guess.UserGuess);
                (this.Session["GuessList"] as List<int>).Add(model.Guess.UserGuess);
                model.Guess.GuessCount = (this.Session["GuessList"] as List<int>).Count();

                HttpCookie requestCookie = Request.Cookies["GuessingGame"];
                try
                {
                    model.HighScore = CookieHelper.ReadCookie<HighScore>(requestCookie, "HighScore");
                    if(model.HighScore == null)
                    {
                        throw (new Exception("HighScore was null!"));
                    }
                }
                catch(Exception e)
                {
                    model.HighScore = new HighScore();
                }
                //highscore check
                if(model.Guess.Result == GuessResult.CORRECT)
                {
                    model.HighScore.InsertScore((this.Session["GuessList"] as List<int>).Count());
                    HttpCookie responseCookie = Response.Cookies["GuessingGame"];
                    CookieHelper.WriteCookie(responseCookie, "HighScore", model.HighScore, DateTime.Now.AddYears(1));
                    //return RedirectToAction("Index");
                }
                return View(model);
            }
            else
            {
                return RedirectToAction("Index");
            }
            
            
        }
    }
}

Layout and views/Views/Shared/PersonTableEntry.cshtml
@model Layout_and_views.Models.Person

<li>
    <div class="row">
        <div class="col-md-3">@Model.Name</div>
        <div class="col-md-3">@Model.City</div>
        <div class="col-md-3">@Model.PhoneNumber</div>
        <div class="col-md-3">
            @Html.ActionLink(linkText: "Remove", actionName: "Remove", routeValues: new { id = Model.Id },
                                                                              htmlAttributes: new { @class = "btn btn-default" })
        </div>

    </div>
    <hr />
</li>

Layout and views/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Layout and views Assignment</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo" href="#">
                        <img style="max-height:30px;" class="img-responsive" src="~/Images/Logo.jpg" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Projects", "Projects", "Home")</li>
                        <li>@Html.ActionLink("Fever Check", "FeverCheck", "FeverCheck")</li>
                        <li>@Html.ActionLink("Guessing Game", "Index", "Guessing")</li>
                        <li>@Html.ActionLink("People", "Index", "People")</li>
                    </ul>
                </div>
            </div>
        </div>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> @DateTime.Now.ToShortDateString() - Fredrik Carlsson</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>